"""回测报告引擎 — 生成 HTML 可视化报告。

功能：
1. 净值曲线（策略 vs 基准 vs 买入持有）
2. 回撤曲线
3. 交易记录明细表（含买卖点标注）
4. 关键指标仪表盘（年化收益/最大回撤/夏普比率/胜率/盈亏比）
5. 决策时间线（L1 触发事件）
6. 每日仓位变化图

使用纯 HTML + CSS + Chart.js (CDN) 渲染，无需后端服务。
"""

import json
import logging
from typing import Dict, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)

# HTML 模板常量
_HTML_HEAD = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>回测报告 - {symbol}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<style>
  :root {{
    --red: #e74c3c;
    --green: #27ae60;
    --blue: #3498db;
    --gray: #95a5a6;
    --dark: #2c3e50;
    --light: #ecf0f1;
    --bg: #f8f9fa;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, "PingFang SC", "Microsoft YaHei", sans-serif; background: var(--bg); color: var(--dark); line-height: 1.6; }}
  .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
  h1 {{ text-align: center; padding: 20px 0; font-size: 1.8em; border-bottom: 3px solid var(--blue); margin-bottom: 24px; }}
  h2 {{ font-size: 1.3em; color: var(--dark); margin: 30px 0 15px; padding-left: 12px; border-left: 4px solid var(--blue); }}
  /* KPI 卡片 */
  .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 30px; }}
  .kpi-card {{ background: white; border-radius: 10px; padding: 18px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .kpi-label {{ font-size: 0.85em; color: var(--gray); margin-bottom: 4px; }}
  .kpi-value {{ font-size: 1.6em; font-weight: bold; }}
  .positive {{ color: var(--red); }}  /* A股红涨 */
  .negative {{ color: var(--green); }} /* A股绿跌 */
  .neutral {{ color: var(--gray); }}
  /* 图表 */
  .chart-container {{ background: white; border-radius: 10px; padding: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); margin-bottom: 24px; position: relative; height: 400px; }}
  .chart-container.tall {{ height: 500px; }}
  /* 表格 */
  table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  th {{ background: var(--dark); color: white; padding: 10px 14px; text-align: left; font-weight: 500; font-size: 0.9em; }}
  td {{ padding: 9px 14px; border-bottom: 1px solid #eee; font-size: 0.88em; }}
  tr:hover td {{ background: #f0f7ff; }}
  .text-right {{ text-align: right; }}
  .text-center {{ text-align: center; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 0.82em; font-weight: 600; }}
  .badge-buy {{ background: #fde8e8; color: var(--red); }}
  .badge-sell {{ background: #e8f5e9; color: var(--green); }}
  .badge-hold {{ background: #f0f0f0; color: var(--gray); }}
  /* 页脚 */
  footer {{ text-align: center; color: var(--gray); padding: 30px; font-size: 0.85em; border-top: 1px solid #ddd; margin-top: 40px; }}
</style>
</head>
<body>
<div class="container">
<h1>📊 {symbol} A股回测报告</h1>

<!-- KPI 仪表盘 -->
<div class="kpi-grid">
{kpi_cards}
</div>
"""

_KPI_TEMPLATE = """<div class="kpi-card">
  <div class="kpi-label">{label}</div>
  <div class="kpi-value {css_class}">{value}</div>
</div>"""

_CHART_TEMPLATE = """
<h2>{title}</h2>
<div class="chart-container{tall_class}">
  <canvas id="{chart_id}"></canvas>
</div>
"""

_TABLE_TRADES = """
<h2>📋 交易记录明细</h2>
<table>
<thead><tr><th>#</th><th>买入日期</th><th>卖出日期</th><th>方向</th>
<th>买入价</th><th>卖出价</th><th>股数</th><th>盈亏(¥)</th><th>收益率</th><th>退出原因</th></tr></thead>
<tbody>{rows}</tbody>
</table>
"""

_TABLE_DECISIONS = """
<h2>🧠 L1 决策记录</h2>
<table>
<thead><tr><th>日期</th><th>类型</th><th>方向</th><th>目标仓位</th>
<th>信号</th><th>PM评级</th><th>触发原因</th></tr></thead>
<tbody>{rows}</tbody>
</table>
"""

_FOOTER = """
<footer>
  <p>Generated by TradingAgents Backtest Engine | {timestamp}</p>
</footer>
</div>

<script>
{chart_scripts}
</script>
</body>
</html>
"""


class ReportEngine:
    """HTML 报告生成器。

    Usage::

        engine = ReportEngine()
        html = engine.generate(backtest_result_dict)
        with open("report.html", "w") as f:
            f.write(html)
    """

    def generate(self, result: Dict) -> str:
        """根据回测结果生成完整 HTML 报告。

        Args:
            result: BacktestEngine.run() 返回的结果字典

        Returns:
            完整的 HTML 字符串，可直接写入 .html 文件
        """
        symbol = result.get("config", {}).get("symbol", "Unknown")
        summary = result.get("summary", {})
        daily_states = result.get("daily_states", [])
        trades = result.get("trade_history", [])
        benchmark_daily = result.get("benchmark_daily", [])
        decisions = result.get("decisions", [])

        parts = []

        # Head + KPI
        parts.append(self._build_head(symbol, summary))

        # 图表部分
        chart_scripts_parts = []

        # 1. 净值曲线
        parts.append(self._build_nav_chart(symbol, daily_states, benchmark_daily))
        chart_scripts_parts.append(self._nav_chart_script(daily_states, benchmark_daily))

        # 2. 回撤曲线
        parts.append(self._build_drawdown_chart(daily_states))
        chart_scripts_parts.append(self._drawdown_script(daily_states))

        # 3. 仓位变化
        parts.append(self._build_position_chart(daily_states))
        chart_scripts_parts.append(self._position_script(daily_states))

        # 4. 交易记录表
        if trades:
            parts.append(self._build_trades_table(trades))

        # 5. 决策记录表
        if decisions:
            parts.append(self._build_decisions_table(decisions))

        # Footer + scripts
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        parts.append(_FOOTER.format(timestamp=timestamp,
                                      chart_scripts="\n".join(chart_scripts_parts)))

        return "\n".join(parts)

    def save(self, result: Dict, output_path: str) -> str:
        """生成报告并保存到文件。"""
        html = self.generate(result)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info(f"[Report] Saved to {output_path}")
        return output_path

    # ── KPI 仪表盘 ────────────────────────────────────────────────

    def _build_head(self, symbol: str, summary: Dict) -> str:
        """构建 HTML head 和 KPI 卡片区域。"""
        kpis = self._make_kpi_data(summary)

        cards = []
        for label, value, css_class in kpis:
            cards.append(_KPI_TEMPLATE.format(
                label=label, value=value, css_class=css_class
            ))

        return _HTML_HEAD.format(symbol=symbol, kpi_cards="\n".join(cards))

    @staticmethod
    def _make_kpi_data(summary: Dict) -> List[tuple]:
        """从汇总数据中提取 KPI 展示数据。"""
        fmt_pct = lambda v, sign=True: (
            f"{v*100:.2f}%" if abs(v) < 10 else f"{v*100:.1f}%"
        ) if v is not None else "N/A"
        cls = lambda v: ("positive" if v > 0 else "negative" if v < 0 else "neutral")

        total_ret = summary.get("total_return", 0)
        ann_ret = summary.get("annual_return", 0)
        max_dd = summary.get("max_drawdown", 0)
        sharpe = summary.get("sharpe_ratio", 0)
        win_rate = summary.get("win_rate", 0)
        alpha = summary.get("alpha", 0)
        bm_ret = summary.get("benchmark_total_return", 0)

        return [
            ("总收益率", fmt_pct(total_ret), cls(total_ret)),
            ("年化收益", fmt_pct(ann_ret), cls(ann_ret)),
            ("最大回撤", fmt_pct(max_dd), "negative"),  # 回撤总是红色警示
            ("夏普比率", f"{sharpe:.2f}" if sharpe else "N/A",
             "positive" if sharpe > 1 else "negative" if sharpe < 0 else "neutral"),
            ("交易胜率", f"{win_rate*100:.1f}%", cls(win_rate - 0.5)),
            ("超额收益(α)", fmt_pct(alpha), cls(alpha)),
            ("基准收益", fmt_pct(bm_ret), cls(bm_ret)),
            ("交易次数", str(summary.get("total_trades", 0)), "neutral"),
        ]

    # ── 图表构建 ──────────────────────────────────────────────────

    @staticmethod
    def _build_nav_chart(symbol: str, states: List[Dict], bm_states: List[Dict]) -> str:
        return _CHART_TEMPLATE.format(
            title=f"💰 净值曲线 ({symbol})",
            chart_id="navChart",
            tall_class=" tall",
        )

    @staticmethod
    def _build_drawdown_chart(states: List[Dict]) -> str:
        return _CHART_TEMPLATE.format(
            title="📉 回撤曲线",
            chart_id="ddChart",
            tall_class="",
        )

    @staticmethod
    def _build_position_chart(states: List[Dict]) -> str:
        return _CHART_TEMPLATE.format(
            title="📊 每日仓位比例",
            chart_id="posChart",
            tall_class="",
        )

    # ── 表格构建 ──────────────────────────────────────────────────

    @staticmethod
    def _build_trades_table(trades: List[Dict]) -> str:
        rows_html = []
        for i, t in enumerate(trades):
            pnl_cls = "positive" if t.get("pnl", 0) > 0 else "negative" if t.get("pnl", 0) < 0 else "neutral"
            direction_cls = "badge-buy" if t["direction"] == "BUY" else "badge-sell"

            rows_html.append(f"""
            <tr>
              <td class="text-center">{i+1}</td>
              <td>{t['entry_date']}</td>
              <td>{t['exit_date'] or '-'}</td>
              <td><span class="badge {direction_cls}">{t['direction']}</span></td>
              <td class="text-right">{t['entry_price']:.2f}</td>
              <td class="text-right">{f"{t['exit_price']:.2f}" if t.get('exit_price') is not None else '-'}</td>
              <td class="text-center">{t['shares']:,}</td>
              <td class="text-right {pnl_cls}">{'+' if t.get('pnl', 0) > 0 else ''}{t.get('pnl', 0):,.2f}</td>
              <td class="text-right {pnl_cls}">{t.get('pnl_pct', 0)*100:.2f}%</td>
              <td>{t.get('exit_reason', '-')}</td>
            </tr>""")

        return _TABLE_TRADES.format(rows="".join(rows_html))

    @staticmethod
    def _build_decisions_table(decisions: List[Dict]) -> str:
        rows_html = []
        for d in decisions:
            dtype = d.get("type", "")
            dir_badge_cls = "badge-buy" if d.get("direction") in ("BUY",) \
                else "badge-sell" if d.get("direction") in ("SELL",) else "badge-hold"

            rows_html.append(f"""
            <tr>
              <td>{d.get('date', '')}</td>
              <td><span class="badge badge-hold">{dtype}</span></td>
              <td><span class="badge {dir_badge_cls}">{d.get('direction', '-')}</span></td>
              <td class="text-center">{d.get('position_pct', '-')}</td>
              <td>{d.get('signal_raw', '-')}</td>
              <td>{d.get('pm_rating', '-')}</td>
              <td>{d.get('trigger', '-')}</td>
            </tr>""")

        return _TABLE_DECISIONS.format(rows="".join(rows_html))

    # ── Chart.js 脚本 ─────────────────────────────────────────────

    @staticmethod
    def _nav_chart_script(states: List[Dict], bm_states: List[Dict]) -> str:
        """生成净值曲线的 Chart.js 配置。"""
        dates = [s["date"] for s in states]
        nav_values = [round(s["total_value"], 2) for s in states]
        bm_values = [round(s["total_value"], 2) for s in bm_states] if bm_states else nav_values

        # 基线（初始资金）
        initial = nav_values[0] if nav_values else 1000000

        return f"""// Net Value Chart
(function(){{
  const ctx = document.getElementById('navChart').getContext('2d');
  new Chart(ctx, {{
    type: 'line',
    data: {{
      labels: {json.dumps(dates)},
      datasets: [
        {{
          label: '策略净值',
          data: {json.dumps(nav_values)},
          borderColor: '#e74c3c',
          backgroundColor: 'rgba(231,76,60,0.05)',
          fill: true,
          tension: 0.1,
          pointRadius: 0,
          borderWidth: 2,
        }},
        {{
          label: '买入持有',
          data: {json.dumps(bm_values)},
          borderColor: '#3498db',
          backgroundColor: 'rgba(52,152,223,0.02)',
          fill: false,
          tension: 0.1,
          pointRadius: 0,
          borderWidth: 1.5,
          borderDash: [5, 5],
        }},
        {{
          label: '初始资金',
          data: Array({len(dates)}).fill({initial}),
          borderColor: '#95a5a6',
          borderDash: [2, 4],
          pointRadius: 0,
          borderWidth: 1,
        }},
      ]
    }},
    options: {{
      responsive: true,
      maintainAspectRatio: false,
      interaction: {{ mode: 'index', intersect: false }},
      plugins: {{ legend: {{ position: 'top' }}, tooltip: {{ callbacks: {{ label: function(c){{ return c.dataset.label + ': ¥' + c.parsed.y.toLocaleString(); }} }} }} }},
      scales: {{ x: {{ ticks: {{ maxTicksLimit: 20, maxRotation: 0 }} }}, y: {{ ticks: {{ callback: function(v){{ return '¥' + v.toLocaleString(); }} }} }} }}
    }}
  }});
}})();"""

    @staticmethod
    def _drawdown_script(states: List[Dict]) -> str:
        """生成回撤曲线脚本。"""
        if not states:
            return "// No drawdown data"

        peak = states[0]["total_value"]
        dd_data = []
        for s in states:
            if s["total_value"] > peak:
                peak = s["total_value"]
            dd = round((peak - s["total_value"]) / peak * 100, 2) if peak > 0 else 0
            dd_data.append(dd)

        dates = [s["date"] for s in states]

        return f"""// Drawdown Chart
(function(){{
  const ctx = document.getElementById('ddChart').getContext('2d');
  new Chart(ctx, {{
    type: 'area',
    data: {{
      labels: {json.dumps(dates)},
      datasets: [{{
        label: '回撤 (%)',
        data: {json.dumps(dd_data)},
        backgroundColor: function(context) {{
          const val = context.raw || 0;
          return val > 15 ? 'rgba(231,76,60,0.4)' : val > 8 ? 'rgba(243,156,18,0.3)' : 'rgba(39,174,96,0.15)';
        }},
        borderColor: '#e74c3c',
        fill: true,
        tension: 0.05,
        pointRadius: 0,
        borderWidth: 1.5,
      }}]
    }},
    options: {{
      responsive: true,
      maintainAspectRatio: false,
      plugins: {{ legend: {{ display: false }}, tooltip: {{ callbacks: {{ label: function(c){{ return '回撤: ' + c.parsed.y.toFixed(2) + '%'; }} }} }} }},
      scales: {{ x: {{ ticks: {{ maxTicksLimit: 20 }} }}, y: {{ reverse: true, ticks: {{ callback: function(v){{ return v.toFixed(1) + '%'; }} }} }} }}
    }}
  }});
}})();"""

    @staticmethod
    def _position_script(states: List[Dict]) -> str:
        """生成仓位比例图表。"""
        dates = [s["date"] for s in states]
        pos_pct = [round(s["position_pct"] * 100, 1) for s in states]

        return f"""// Position Chart
(function(){{
  const ctx = document.getElementById('posChart').getContext('2d');
  new Chart(ctx, {{
    type: 'line',
    data: {{
      labels: {json.dumps(dates)},
      datasets: [{{
        label: '仓位 (%)',
        data: {json.dumps(pos_pct)},
        backgroundColor: 'rgba(52,152,223,0.15)',
        borderColor: '#3498db',
        fill: true,
        tension: 0.1,
        pointRadius: 0,
        borderWidth: 1.5,
      }}]
    }},
    options: {{
      responsive: true,
      maintainAspectRatio: false,
      plugins: {{ legend: {{ display: false }} }},
      scales: {{ x: {{ ticks: {{ maxTicksLimit: 20 }} }}, y: {{ min: 0, max: 105, ticks: {{ callback: function(v){{ return v + '%'; }} }} }} }}
    }}
  }});
}})();"""
